### PR TITLE
Argument parsing, include opt and dry run opt

### PR DESCRIPTION
**Pull request by paulgessinger**
Introduce more flexible argument parsing, which enables:
- dry run option
- option which lets the user specify which repositories to include

Also add an .editorconfig file which states indent style to tabs

### CODE REVIEW

**Comment by ericlathrop** [comment]
This looks pretty nice! I'll try to test & merge it within the next week. If you don't hear back from me, just ping me again.

**Comment by paulgessinger** [comment]
ping?

**Comment by ericlathrop** [comment]
I'm getting a crash on organization repos with this PR. This command fails:

```
node bin/github-backup.js -n --include org ericlathrop my-backups
```

gives this stack trace:

```
Unhandled error: TypeError: Cannot read property 'match' of undefined
    at backupRepo (/home/eric/src/github-backup/lib/backup.js:10:19)
    at backupRepoSerialized (/home/eric/src/github-backup/lib/backup.js:37:10)
    at /home/eric/src/github-backup/lib/backup.js:50:14
    at tryCatcher (/home/eric/src/github-backup/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/eric/src/github-backup/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/eric/src/github-backup/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/eric/src/github-backup/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/eric/src/github-backup/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/eric/src/github-backup/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/eric/src/github-backup/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by ericlathrop** [comment]
I got it fixed. Gonna do a bit more testing, then merge.

**Comment by paulgessinger** [comment]
Hm, I'm not in any organization, that's probably why I didn't see it during my own testing..

**Comment by ericlathrop** [comment]
[Here was the fix for that issue.](https://github.com/ericlathrop/github-backup/commit/34091d9a3d295581924fec7fdbf2e6d7d4a19643) I packaged the changes as 0.2.0 and published it to NPM.

**Pull request merged**
